buildscript {
    ext {
        springBootVersion = '3.5.16'
        springDependencyManagementVersion = '1.1.7'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
        classpath "io.spring.gradle:dependency-management-plugin:${springDependencyManagementVersion}"
    }
}

allprojects {
    group = 'gg.popn'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'
    
    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        }
    }
    
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
    
    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        implementation 'org.springframework.boot:spring-boot-starter-security'
    }
    
    test {
        useJUnitPlatform()
    }
}

configure(subprojects.findAll { it.name != 'popngg-domain' && it.name != 'popngg-infra' }) {
    apply plugin: 'org.springframework.boot'
}

project(':popngg-api') {
    bootJar { enabled = true }
    jar { enabled = false }
}

['popngg-domain', 'popngg-infra'].each { module ->
    project(":$module") {
        bootJar { enabled = false }
        jar { enabled = true }
    }
}
