global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: popngg-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api:9091"]
        labels:
          service: popngg-api
          environment: production

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          environment: production

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          environment: production
