spring:
  config:
    activate:
      on-profile: local
  
  docker:
    compose:
      file: classpath:docker-compose.yml
      lifecycle-management: start-and-stop

  datasource:
    url: jdbc:mysql://mysql:3306/popnggdb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true

# Logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Server
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# JWT properties for local
jwt:
  secret-key: 12345678901234567890123456789012345678901234567890123456789012345
  expiration-hours: 24
  issuer: popngg

# Application properties
app:
  cors:
    allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"
