server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: popngg-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: popngg-api
          environment: production
          __path__: /var/log/popngg/*.log
